### ISSUE TITLE
akka 持久化redis 问题

### ISSUE THREAD

**Issue by Fxdemon** [apache/servicecomb-pack#575]
redis设置是无效的 依然读取jar 包中reference.conf
中的配置 

![图片](https://user-images.githubusercontent.com/3349402/67072145-d5833b00-f1b6-11e9-8f06-1c90a38f9084.png)

 
![图片](https://user-images.githubusercontent.com/3349402/67072179-e2a02a00-f1b6-11e9-86a3-df45801e82fa.png)

**Comment by coolbeevip** [comment]
谢谢你提供这个消息，你能够把你的redis参数配置发给我看看吗？

**Comment by coolbeevip** [comment]
我大概知道原因了，如果你使用源代码方式编译启动 Alpha，那么你可以尝试在 application.yaml 中增加以下两个配置试试，就是以下实例的最后4行。

```yaml
akka-persistence-redis:
  redis:
    mode: "simple"
    host: "127.0.0.1"
    port: 6379
    database: 0
  journal:
    redis: ${akka-persistence-redis.redis}
  snapshot:
    redis: ${akka-persistence-redis.redis}
```
